modLoader = "javafml"
loaderVersion = "[47,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/handcrafted/issues"

[[mods]]
modId = "handcrafted"
version = "${version}"
displayName = "Handcrafted"
displayURL = "https://modrinth.com/mod/handcrafted"
logoFile = "icon.png"
authors = "Alex Nijjar, Kekie6"
credits = "CodexAdrian, Facu, Marc-IceBlade, MsRandom, ThatGravyBoat"
description = "Epic Furniture mod!"

[[dependencies.handcrafted]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"