modLoader = "javafml"
loaderVersion = "[45,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/Handcrafted/issues"

[[mods]]
modId = "handcrafted"
version = "${version}"
displayName = "Handcrafted"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/handcrafted"
logoFile = "icon.png"
authors = "Alex Nijjar, Kekie6"
credits = "CodexAdrian, Facu, Marc-IceBlade, MsRandom, ThatGravyBoat"
description = "Epic Furniture mod!"

[[dependencies.handcrafted]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"