modLoader = "javafml"
loaderVersion = "[1,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/handcrafted/issues"

[[mods]]
modId = "handcrafted"
version = "${version}"
displayName = "Handcrafted"
displayURL = "https://modrinth.com/mod/handcrafted"
logoFile = "icon.png"
authors = "Alex Nijjar, Kekie6"
credits = "CodexAdrian, Facu, Marc-IceBlade, MsRandom, ThatGravyBoat"
description = "Epic Furniture mod!"

[[mixins]]
config = "handcrafted-common.mixins.json"

[[dependencies.handcrafted]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "NONE"
side = "BOTH"