modLoader = "javafml"
loaderVersion = "[1,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/handcrafted/issues"

[[mods]]
modId = "handcrafted"
version = "${version}"
displayName = "Handcrafted"
displayURL = "https://modrinth.com/mod/handcrafted"
logoFile = "icon.png"
authors = "Alex Nijjar, Kekie6"
credits = "CodexAdrian, Facu, Marc-IceBlade, MsRandom, ThatGravyBoat"
description = "Epic Furniture mod!"

[[mixins]]
config = "handcrafted-common.mixins.json"

[[dependencies.handcrafted]]
modId = "neoforge"
type="required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "resourcefullib"
type="required"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"